// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGPIvZvdbyrXwRJonYmSZvUHhGEmapec8',
    appId: '1:238745148522:web:9647d1c06a823cbf26be13',
    messagingSenderId: '238745148522',
    projectId: 'forexcompanion-e5a28',
    authDomain: 'forexcompanion-e5a28.firebaseapp.com',
    databaseURL: 'https://forexcompanion-e5a28-default-rtdb.firebaseio.com',
    storageBucket: 'forexcompanion-e5a28.firebasestorage.app',
    measurementId: 'G-CX1BXTQTRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPNE9HFodkZfyXfocDYW6RU60HbnlwCVM',
    appId: '1:238745148522:android:b9f5cefab3cfa54426be13',
    messagingSenderId: '238745148522',
    projectId: 'forexcompanion-e5a28',
    databaseURL: 'https://forexcompanion-e5a28-default-rtdb.firebaseio.com',
    storageBucket: 'forexcompanion-e5a28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNLL1ExM0cr0RRlLFVeHVAU3jqiC17IJI',
    appId: '1:238745148522:ios:2c06bdf4fcd8fe8d26be13',
    messagingSenderId: '238745148522',
    projectId: 'forexcompanion-e5a28',
    databaseURL: 'https://forexcompanion-e5a28-default-rtdb.firebaseio.com',
    storageBucket: 'forexcompanion-e5a28.firebasestorage.app',
    iosBundleId: 'com.forexadvisor.forexcompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNLL1ExM0cr0RRlLFVeHVAU3jqiC17IJI',
    appId: '1:238745148522:ios:cd6d8d40ea26f3bc26be13',
    messagingSenderId: '238745148522',
    projectId: 'forexcompanion-e5a28',
    databaseURL: 'https://forexcompanion-e5a28-default-rtdb.firebaseio.com',
    storageBucket: 'forexcompanion-e5a28.firebasestorage.app',
    iosBundleId: 'com.forexadvisor.forexCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGPIvZvdbyrXwRJonYmSZvUHhGEmapec8',
    appId: '1:238745148522:web:26c408045be9a6f026be13',
    messagingSenderId: '238745148522',
    projectId: 'forexcompanion-e5a28',
    authDomain: 'forexcompanion-e5a28.firebaseapp.com',
    databaseURL: 'https://forexcompanion-e5a28-default-rtdb.firebaseio.com',
    storageBucket: 'forexcompanion-e5a28.firebasestorage.app',
    measurementId: 'G-TTJZXWQ4HG',
  );
}
